### ISSUE TITLE
放三张图片有问题

### ISSUE THREAD

**Issue by zhangzzqq** [wanliyang1990/AdViewPager#1]
放三张图片的时候，从第一个点直接跳到最后一个

**Comment by ywl5320** [comment]
没有呢，都是正常的

**Comment by ywl5320** [comment]
1张、2张、3张都是可以的

**Comment by liyv** [comment]
### boolean isRight可以去掉吗？作者能否解惑下，谢谢！@wanliyang1990

**Comment by ywl5320** [comment]
这个是判断是向左滑动还是右滑动的，就能判断到临界点时该替换第一张还是最后一张，就能精确调用方法。原来我也是没有设置这个变量的，但是在项目中使用时，偶尔出现过在临界点显示不正确的问题（具体问题现在忘了），所以才加了这一个判断。

**Comment by SmithGao** [comment]
您好请问一下 为什么我把项目导进as 出现红色的叹号 跑不起来

**Comment by ywl5320** [comment]
是不是gradle不对，如果实在不行，你就新建一个工程，把源代码拷贝过去也可以。

**Comment by SmithGao** [comment]
朋友 qq聊一下吧 2215719882 谢谢哈 我已经全部倒过来了 但是在uitl 这个类里   for (int i = 0; i < dotViews.length; i++) {  报错 空指针

**Comment by JingShan666** [comment]
怎么实现添加本地图片

**Comment by ywl5320** [comment]
把读取图片的那个方法 改成读取本地就行了 glide可以直接加载本地图片的

**Comment by JingShan666** [comment]
能加一下qq么，我的949513327，向您咨询一下
